@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.brunhine.moresigils.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;